name: Publish package

on:
  release:
    types: [published]

jobs:
  publish_package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Publish
        run: |
          npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
          npm publish dist/@ajsf/core --access public
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}